---
- hosts: all
  user: vagrant
  become: yes
  become_user: root
  gather_facts: True

  vars:
    db: iedb
    dbuser: iedbadmin

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted
    - name: restart mariadb
      service: name=mariadb state=restarted

  tasks:
    # Required to install python 3
    - name: Install IUS repository setup script
      get_url:
        url: https://setup.ius.io/
        dest: /opt/setup-ius.sh

    - name: Run IUS repository setup script
      command: bash /opt/setup-ius.sh
      args:
        creates: /etc/yum.repos.d/ius.repo

    - name: Install needed software packages
      yum: name={{ item }} state=latest
      with_items:
        - git
        - wget
        # MariaDB is a fork of MySQL used by CentOS. We use it for the initial loading
        # of the dump files downloaded from the production IEDB (which is also running a MariaDB
        # instance), and then use pgloader to move the files from the MariaDB server to the
        # PostgresSQL server.
        - mariadb-server
        - mariadb
        - postgresql-server
        - postgresql
        - python-psycopg2
        - python36
        - python36-psycopg2
        - python36-pip

    - name: Install further python 3 modules using pip
      pip:
        executable: pip3
        name:
          - flask
          - openpyxl

    - name: Initialise the PostgreSQL db
      command: postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/initdb.log

    - name: Change local postgresql socket authentication to trust
      lineinfile:
        dest: /var/lib/pgsql/data/pg_hba.conf
        regexp: '^(local\s+all\s+all\s+)\w+$'
        line: '\1trust'
        backrefs: yes

    - name: Change local postgresql host authentication to trust
      lineinfile:
        dest: /var/lib/pgsql/data/pg_hba.conf
        regexp: '^(host\s+all\s+all\s+127\.0\.0\.1\/32\s+)\w+$'
        line: '\1trust'
        backrefs: yes

    - name: Start the PostgreSQL service
      service: name=postgresql state=started enabled=yes

    - name: Create the iedb database on the PostgreSQL server
      become_user: postgres
      postgresql_db:
        name: "{{ db }}"

    - name: Create the iedb administrator user on the PostgreSQL server
      become_user: postgres
      postgresql_user:
        db: "{{ db }}"
        name: "{{ dbuser }}"

    - name: Set the iedb database owner to the iedb administrator on the PostgreSQL server
      become_user: postgres
      postgresql_db:
        name: "{{ db }}"
        owner: "{{ dbuser }}"

    - name: Download and extract Clozure CL needed for pgloader
      unarchive:
        src: https://github.com/Clozure/ccl/releases/download/v1.11.5/ccl-1.11.5-linuxx86.tar.gz
        dest: /opt
        creates: /opt/ccl
        remote_src: yes

    - name: Copy ccl64 to /usr/bin/ccl
      copy:
        src: /opt/ccl/scripts/ccl64
        dest: /usr/bin/ccl
        force: no
        mode: u=rwx,g=rx,o=rx
        remote_src: yes

    - name: Change CCL_DEFAULT_DIRECTORY in /usr/bin/ccl
      lineinfile:
        dest: /usr/bin/ccl
        regexp: '^(  CCL_DEFAULT_DIRECTORY=)'
        line: '\1/opt/ccl'
        backrefs: yes

    - name: Clone pgloader git repository
      git:
        repo: https://github.com/dimitri/pgloader.git
        version: v3.6.1
        dest: /opt/pgloader

    - name: Install CentOS 7 pgloader dependencies
      command: bash bootstrap-centos7.sh chdir="/opt/pgloader"
      args:
        creates: /usr/lib64/libsybdb.so

    - name: Build pgloader from source
      make:
        chdir: /opt/pgloader
        target: pgloader
        params:
          CL: ccl
          DYNSIZE: 128

    - name: Copy pgloader to /usr/bin/pgloader
      copy:
        src: /opt/pgloader/build/bin/pgloader
        dest: /usr/bin/pgloader
        force: no
        mode: u=rwx,g=rx,o=rx
        remote_src: yes

    - name: Change MariaDB max_allowed_packet_size
      lineinfile:
        dest: /etc/my.cnf
        line: 'max_allowed_packet=64M'
        insertafter: '^\[mysqld\]$'

    - name: Start the MariaDB service
      service: name=mariadb state=started enabled=yes

    - name: Add aliases and environment variables to /home/vagrant/.bashrc
      lineinfile:
        dest: /home/vagrant/.bashrc
        insertafter: EOF
        line: >-
          PS1='\[\033[02;32m\][\u@\h \w]\$\[\033[00m\] ';
          export PGDATABASE=iedb;
          export PGUSER=iedbadmin;
          alias rm='rm -i';
          alias mv='mv -i';
          alias cp='cp -i';
          alias ls='ls -CF'

    - name: Add color prompt to root .bashrc
      lineinfile:
        dest: /root/.bashrc
        insertafter: EOF
        line: >-
          PS1='\[\033[00;31m\][\u@\h \w]\$\[\033[00m\] '